### ISSUE TITLE
Brass recipe

### ISSUE THREAD

**Issue by NukolLodda** [StavWasPlayZ/Even-More-Instruments#12]
So I was looking at the crafting recipes and since I am going to include your mod into a modpack, I was thinking some of the recipes are a bit too expensive so what if the recipes for the saxophone and the trombony are switched to being made with brass if this mod is played alongside another mod that adds brass/registers brass into the tags.

**Comment by StavWasPlayZ** [comment]
Hey! I'm uncertain if I can 100% do it, because recipes are data-driven and not hardcoded.

But I can definitely look into it.  
I also agree that the recipes are a lil' pricey 😅

Would you please be able to provide me the name of the mod you're speaking of?  
Also, if you could suggest another vanilla recipes for these problematic instruments - what would you make them?

Looking forward 🙃

**Comment by NukolLodda** [comment]
I would say that create is a good example of the mod I'm talking about that
adds brass, but if possible I would also like to make this idea work in
general.

**Comment by NukolLodda** [comment]
also, are they data driven as in you write the json files yourself and then
you put them in the recipes folder, or are they generated by a java file
b/c if they are generated by a java file then my idea shouldn't be too hard
to implement.

**Comment by StavWasPlayZ** [comment]
Data generation in Minecraft is just that - making the JSONs in your term.

I don't do that, rather I make the JSONs myself.

But now that I think of it, if I just include an "invalid" block ID and it is unpresent, Minecraft will just ignore it.

So yeah, it's very much possible.

Either way, please do share a recipe suggestion if you can! 🙂

**Comment by NukolLodda** [comment]
the recipe idea I have in mind is literally just replace the copper and the
gold in those recipes w/ blocks/brass for the blocks and ingots/brass for
the ingots

**Comment by StavWasPlayZ** [comment]
Well, fine enough then.

I'll just have you know that I never really played this mod myself, and I'm a bit contextless on that regard.. So apologies.

Nevertheless, I'll fetch the item/block IDs and implement them sometime when I find the time.

**Comment by StavWasPlayZ** [comment]
Also, could I please get your target Minecraft version? So I know which to prioritize.

**Comment by NukolLodda** [comment]
most recent, 1.21 fabric is the version I'm on

**Comment by StavWasPlayZ** [comment]
> most recent, 1.21 fabric is the version I'm on

I have to say, I didn't particularly see Create for this version... But I'll release it for there anyways, since I have some more fixes I'd like to push.
