### ISSUE TITLE
Extra Input Toggles?

### ISSUE THREAD

**Issue by theDerpu** [StavWasPlayZ/Even-More-Instruments#15]
I find it annoying having to either go upstairs and plug my laptop into a midi, or constatly change key to use flats and sharps,

A solution to this could be having a toggle in the instruments settings for smaller black circles to appear between the white ones where aplicable, they would only be able to be clicked but its better than nothing

Maybe also having it so holding shift sharpens every note you play that can be sharpened without turning into a neutral note (e.g. C => B)

This is probably quite tough to implement though.

(I realise I've posted three issues at once and it's a lot but I've been loving this mod for ages, and wanted to provide what could be amazing improvements haha, sorry ;W;)

**Comment by theDerpu** [comment]
Oops, this should also probably be on the main mod instead, sorry bout that :p

**Comment by StavWasPlayZ** [comment]
Hey - these exist ;D

![image](https://github.com/user-attachments/assets/3f71e22e-8759-4c50-841b-e5ee1a86ee6f)

Should probably better document this 😅  
Perhaps an in-game hint..-

> (I realise I've posted three issues at once and it's a lot but I've been loving this mod for ages, and wanted to provide what could be amazing improvements haha, sorry ;W;)

Toat's fine! All input is apperciated :)  
And thank you!

If what I just said does resolve your issue, feel free to close it.  
If I got this wrong, do let me know.

**Comment by theDerpu** [comment]
Oh yeah totally perfect had no idea haha, thanks :D
