### ISSUE TITLE
Re: Texture changes

### ISSUE THREAD

**Issue by StavWasPlayZ** [StavWasPlayZ/Even-More-Instruments#3]
_Originally posted by @GenMode in https://github.com/StavWasPlayZ/Genshin-Instruments/issues/9#issuecomment-1726774091_:

> ok I updated the other 16x16 instruments too. I'm going to be honest I kinda liked what you had so this wasn't much more than just a quick touch up. Hope you like it
>
> ![Screenshot 2023-09-19 190241](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/2d777a3c-4cb6-4f22-ae8b-1132a6ecbabc)
>
> ![guitar](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/966e8d0b-d97d-45ee-bb20-91b786b08726)
![note_block_instrument](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/2d37af7c-4698-4467-bf7d-03a664d59e85)
![violin](https://github.com/StavWasPlayZ/Genshin-Instruments/assets/106150125/787c16c3-c363-4033-9553-6d907ebeb3bc)

**Comment by StavWasPlayZ** [comment]
Yes, I absolutely do like it!!
I really like the Note Block Instrument and that it is ACTUALLY deriving a note block, that is so cool! And the violin is simply a work of perfectionn I love the colors so muchhh 😭😭

I would, still, like to consult about the textures, though:

- I think the Guitar should have a more rounded entrance to its "stick"(?) part:
![image](https://github.com/StavWasPlayZ/Even-More-Instruments/assets/89315181/c6899ddb-fe4a-4d0d-8f6b-0538bdad18cd)

  - That may go for the Note Block Instrument too:
![image](https://github.com/StavWasPlayZ/Even-More-Instruments/assets/89315181/40484a73-ac28-4a4e-9191-3a73aff1c73a)

- The Guitar should be 1 pixel thicker than it is at current; given more width, the central hole can better be re-produced (slightly larger than is):
![image](https://github.com/StavWasPlayZ/Even-More-Instruments/assets/89315181/8ab87cba-b159-4eaf-bf63-422a8a026393)

- Lastly, I think shifting the violin to the left 1 bit does it right, to fix its slightly tilted shape:
![image](https://github.com/StavWasPlayZ/Even-More-Instruments/assets/89315181/59fff7e0-a4f9-4456-bc6c-d8e6430b12d4)

I'm not a pixel-artist, so I don't really understand much in this regard; so I thus apologize if I am going against artistic design choices. If I am, please let me know!! I'd like to understand this a bit better 😅

**Comment by StavWasPlayZ** [comment]
I've manually tweaked the textures and landed with this:

![violin](https://github.com/StavWasPlayZ/Even-More-Instruments/assets/89315181/115309d2-d48b-4dc0-955d-62b5d40c9169)
![note_block_instrument](https://github.com/StavWasPlayZ/Even-More-Instruments/assets/89315181/1a6d09ca-0f8a-4142-ac47-1a9df881e503)
![guitar](https://github.com/StavWasPlayZ/Even-More-Instruments/assets/89315181/c5176b90-e562-411c-a565-75fe484e2a66)

Feel free to re-open this issue to dispute them.
Thanks again! ☺

**Comment by GenMode** [comment]
Oh I was gonna get to that next tuesday but thank you for modifying them yourself. I hope they look better that way and enjoy the textures lol.
