### ISSUE TITLE
I'm very sorry but I couldn't figure out where to send the textures. Is this ok?

### ISSUE THREAD

**Issue by GenMode** [StavWasPlayZ/Even-More-Instruments#9]
![violin_bow](https://github.com/StavWasPlayZ/Even-More-Instruments/assets/106150125/f436da44-9584-4a9e-a755-516f26f5a396)
![bachi](https://github.com/StavWasPlayZ/Even-More-Instruments/assets/106150125/6380ddb7-c451-48ce-ba38-c6de69545f0f)
![pipa](https://github.com/StavWasPlayZ/Even-More-Instruments/assets/106150125/161c6076-5b5c-4fbb-b976-a444bbde5105)
![shamisen](https://github.com/StavWasPlayZ/Even-More-Instruments/assets/106150125/d147e9e0-a747-4ca2-9485-543488c9fab8)

**Comment by StavWasPlayZ** [comment]
XD this is the right place mate, all's gud. Yes, thank you very much!
